language: python
python:
  - "3.7"
install:
  - pip install .
script:
  - pytest
before_deploy:
  - export TORCHMETA_VERSION_CHANGED=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep torchmeta/version.py | wc -l)
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  server: https://testpypi.python.org/pypi
  distributions: "sdist bdist_wheel"
  on:
    repo: tristandeleu/pytorch-meta
    branch: master
    condition: $((TORCHMETA_VERSION_CHANGED)) -gt 0
